/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import React from "react";

export const Index: Record<string, any> = {
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    files: [{
      path: "src/registry/src/lib/utils.ts",
      type: "registry:lib",
    }],
  },
  "use-controllable-state": {
    name: "use-controllable-state",
    description: "",
    type: "registry:hook",
    files: [{
      path: "src/registry/src/hooks/use-layout-effect.tsx",
      type: "registry:hook",
    },{
      path: "src/registry/src/hooks/use-controllable-state.ts",
      type: "registry:hook",
    }],
  },
}